[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-run --chip STM32H743ZITx" # to list chips, run `probe-run --list-chips.`
#runner = "probe-run --chip STM32H745ZITx" # to list chips, run `probe-run --list-chips.`
#runner = "probe-run --chip STM32G431CBUx" # to list chips, run `probe-run --list-chips.`
# todo: No 491 target. Ok to use 431? Maybe 484 or something that supports higher flash?
runner = "probe-run --chip STM32G431CBUx" # to list chips, run `probe-run --list-chips.`

rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
rr = "run --release"