[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# to list chips, run `probe-run --list-chips.`
#runner = "probe-rs run --chip STM32G473CEUx"
runner = "probe-rs run --chip STM32H743VIHx"

rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
rr = "run --release"
br = "build --release"

# todo: These aliases are not working
#rgq = "run --release --features g4 quad print-status"
#rhq = "run --release --features h7 quad print-status"
#rgf = "run --release --features g4 fixed-wing print-status"
#rhf = "run --release --features h7 fixed-wing print-status"